---
- name: add apt repository
  become: yes
  apt_repository:
    repo: ppa:git-core/ppa

- name: install git
  become: yes
  apt:
    name: git
    state: latest # noqa 403

- name: install gitk
  become: yes
  apt:
    name: gitk
