---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: cplusplus-bionic
    image: ubuntu:18.04
    capabilities:
      - SYS_PTRACE
    security_opts:
      - seccomp=unconfined
  # TODO: support this
  # - name: cplusplus-leap-15.2
  #   image: opensuse/leap:15.2
  #   capabilities:
  #     - SYS_PTRACE
  #   security_opts:
  #     - seccomp=unconfined
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
