---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: git-bionic
    image: ubuntu:18.04
    dockerfile: DockerfileExtended.j2
  - name: git-opensuse-leap-15.2
    image: opensuse/leap:15.2
    dockerfile: DockerfileExtended.j2
provisioner:
  name: ansible
  options:
    user: vagrant
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
