---
- name: check whether already installed sourcetrail
  command: |-
    which sourcetrail
  register: checked_result
  changed_when: False
  failed_when: checked_result.rc not in [0, 1]

- name: install shellcheck
  when: checked_result.rc == 1
  block:
    - name: install requirements
      become: yes
      apt:
        name:
          - libgl1
    - name: create directory to extract archive
      become: yes
      file:
        path: "/usr/local/src/sourcetrail-{{ sourcetrail_tag }}"
        state: directory
    - name: download and unarchive tarball
      become: yes
      unarchive:
        src: "https://github.com/CoatiSoftware/Sourcetrail/releases/download/{{ sourcetrail_tag }}/{{ sourcetrail_tgz }}"
        dest: "/usr/local/src/sourcetrail-{{ sourcetrail_tag }}"
        remote_src: yes
    - name: execute install script
      become: yes
      command: "sh install.sh"
      args:
        chdir: "/usr/local/src/sourcetrail-{{ sourcetrail_tag }}/Sourcetrail"
