---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: gui-applications-bionic
    image: ubuntu:18.04
  # TODO: support this
  # - name: gui-applications-opensuse-leap-15.2
  #   image: opensuse/leap:15.2
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
