---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: python-bionic
    image: ubuntu:18.04
    dockerfile: DockerfileExtended.j2
  # TODO: Support this
  # - name: python-buster
  #   image: debian:10
  #   dockerfile: DockerfileExtended.j2
provisioner:
  name: ansible
  options:
    user: vagrant
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
