---

- hosts: all
  roles:
    - distribution
    - setup

- import_playbook: well_tested.yml

# common roles (not-tested by molecule)
- hosts: all
  roles:
    - bash-completion
    - font
    - i3
    - inputrc
    - localization
    - samba
    - xdm
    - xfce4-terminal
