---
# common roles (tested by molecule)
- hosts: all
  roles:
    - cplusplus
    - docker
    - firefox
    - git
    - inotify
    - nkf
    - prompt
    - pv
    - python
    - rust
    - shellcheck
    - sourcetrail
    - swap
    - vscode
    - window-system
    - xmllint
    - zip
