---
- name: verify
  hosts: all
  tasks:
    - name: assert test environment
      block:
        - name: determine remote user
          command: whoami
          register: result
          changed_when: False
        - name: assert remote user
          assert:
            that:
              - result.stdout == "vagrant"
            fail_msg: "actual result is {{ result.stdout }}"
    - name: test swap size
      block:
        - name: determine max_user_watches
          command: bash -c "cat /proc/sys/fs/inotify/max_user_watches"
          register: result
          changed_when: False
        - name: assert swap size
          assert:
            that:
              - result.stdout == "524288"
            fail_msg: "actual size is {{ result.stdout }}"
