---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: vscode-xenial
    image: ubuntu:16.04
    dockerfile: DockerfileExtended.j2
  - name: vscode-bionic
    image: ubuntu:18.04
    dockerfile: DockerfileExtended.j2
  # TODO: support this
  # - name: vscode-opensuse-leap-15.2
  #   image: opensuse/leap:15.2
  #   dockerfile: DockerfileExtended.j2
provisioner:
  name: ansible
  options:
    user: vagrant
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
