---
- name: verify
  hosts: all
  gather_facts: false
  tasks:
    - name: assert test environment
      block:
        - name: determine remote user
          command: whoami
          register: result
          changed_when: False
        - name: assert remote user
          assert:
            that:
              - result.stdout == "vagrant"
            fail_msg: "actual result is {{ result.stdout }}"
    - name: test command existence
      command: bash -c "type {{ item }}"
      changed_when: False
      with_items:
        - sourcetrail
    - name: execute command then no errors occur
      command: bash -c "sourcetrail {{ item }}"
      changed_when: False
      with_items:
        - "--help"
        - "--version"
