---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: shellcheck-focal
    image: ubuntu:20.04
    dockerfile: DockerfileExtended.j2
provisioner:
  name: ansible
  options:
    user: vagrant
verifier:
  name: ansible
