---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: shellcheck-bionic
    image: ubuntu:18.04
    dockerfile: DockerfileExtended.j2
  - name: shellcheck-buster
    image: debian:10
    dockerfile: DockerfileExtended.j2
provisioner:
  name: ansible
  options:
    user: vagrant
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
