---

- name: put pyenv.bashrc in ~/.bashrc.d
  copy:
    src: bashrc
    dest: ~/.bashrc.d/pyenv.bashrc
    mode: 0755

- name: check whether already installed pyenv
  shell: |-
    . ~/.bashrc.d/pyenv.bashrc
    if [ $(command -v which) ]; then which pyenv; else type pyenv; fi
  register: checked_result
  changed_when: False
  failed_when: checked_result.rc not in [0, 1]

- name: install pyenv
  when: checked_result.rc == 1
  block:
    - name: install requirements by apt
      become: yes
      apt:
        name:
          - git
      when:
        - ansible_distribution == "Ubuntu"
    - name: install requirements by zypper
      become: yes
      zypper:
        name:
          - git
      when:
        - ansible_distribution == "openSUSE Leap"
    - name: create temporary working directory
      tempfile:
        state: directory
      register: tmpdir
    - name: download pyenv-installer
      get_url:
        url: https://pyenv.run
        dest: "{{ tmpdir.path }}/pyenv-installer"
    - name: execute pyenv-installer
      command: "bash {{ tmpdir.path }}/pyenv-installer"
    - name: remove temporary working directory
      file:
        path: "{{ tmpdir.path }}"
        state: absent
