---

- name: install aptitude for ansible module apt
  become: yes
  apt:
    name: aptitude

- name: update cache and upgrade packages if current one is older than a day
  become: yes
  apt:
    cache_valid_time: 86400
    install_recommends: no
    update_cache: yes
    upgrade: safe

- name: remove useless packages from the cache
  become: yes
  apt:
    autoclean: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
