---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: nkf-xenial
    image: ubuntu:16.04
  - name: nkf-bionic
    image: ubuntu:18.04
  - name: nkf-opensuse-leap-15.2
    image: opensuse/leap:15.2
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
