name: CI

on: [push, pull_request]

jobs:
  test_cplusplus:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=cplusplus
  test_docker:
    # Use macOS instance for VirtualBox
    # because nested virtualization is not supported for Ubuntu instances
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - name: test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: make test ROLE=docker
  test_firefox:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=firefox
  test_git:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=git
  test_nkf:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=nkf
  test_prompt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=prompt
  test_pv:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=pv
  test_python:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=python
  test_rust:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=rust
  test_shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=shellcheck
  test_swap:
    # Use macOS instance for VirtualBox
    # because nested virtualization is not supported for Ubuntu instances
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - name: test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: make test ROLE=swap
  test_vscode:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=vscode
  test_xmllint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=xmllint
  test_zip:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.1.0
      - run: make sync
      - run: make test ROLE=zip
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: make up
      - run: make lint TTY=false
      - run: make down
  status_check:
    runs-on: ubuntu-18.04
    needs:
      - test_cplusplus
      - test_docker
      - test_firefox
      - test_git
      - test_nkf
      - test_prompt
      - test_python
      - test_rust
      - test_shellcheck
      - test_swap
      - test_vscode
      - test_xmllint
      - test_zip
      - lint
    steps:
      - run: echo 'pass'
